sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: azhaer66
  alioss:
    access-key-id: LTAI5t8pkS1ASCmxoG9igwFg
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-secret: tn2EU2RVL8pJ2cGISHEE4qx7AXh4w9
    bucket-name: nuist-delivery
  redis:
    host: localhost
    port: 6379
    password: azhaer66
    database: 10

